variables:
  HELM_REPOSITORY: s3://helm.samarkand.io/charts
  AWS_DEFAULT_REGION: eu-west-2
stages:
  - lint
  - publish

lint:
  image:
    name: lachlanevenson/k8s-helm:v3.3.0
    entrypoint: ["/bin/sh", "-c"]
  stage: lint
  script:
    - helm lint    charts/airflow

publish:
  stage: publish
  image:
    name: lachlanevenson/k8s-helm:v3.3.0
    entrypoint: ["/bin/sh", "-c"]
  before_script:
    - apk add --no-cache git bash
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
    - helm plugin install https://github.com/hypnoglow/helm-s3.git
    - helm repo add samarkand $HELM_REPOSITORY
  script:
    - helm package -u --app-version $CI_COMMIT_TAG --version $CI_COMMIT_TAG .
    - helm s3 push $CI_PROJECT_NAME-$CI_COMMIT_TAG.tgz samarkand
  only:
    - tags
